services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local