services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file: .env
    command: sh -c "pnpm start:dev"
    depends_on:
      - db

  db:
    image: postgres:16
    env_file: .env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
    driver: local